on:
    pull_request:
        paths:
            - '!repo/**'
    push:
        paths:
            - '!repo/**'

concurrency:
    group: deploy-${{ github.ref }}
    cancel-in-progress: true

jobs:
    publish:
        permissions:
            contents: read
            deployments: write
        runs-on: ubuntu-latest
        name: Deploy to Cloudflare Pages
        steps:
            -   name: 'Checkout'
                uses: actions/checkout@v5
            -   name: Set up JDK 21
                uses: actions/setup-java@v4.0.0
                with:
                    java-version: '21'
                    distribution: 'temurin'
            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew
            -   name: Build repo
                uses: gradle/gradle-build-action@v2.11.0
                with:
                    arguments: :repo:buildRepo
            -   name: Deploy
                uses: cloudflare/wrangler-action@v3
                with:
                    apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                    accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                    gitHubToken: ${{ secrets.GITHUB_TOKEN }}
                    command: pages deploy build/repo --project-name="mewodding-repo" --commit-hash=${{ github.sha }} --branch=${{ github.ref_name }}
