on:
    pull_request:
        paths:
            - 'repo/**'
    push:
        paths:
            - 'repo/**'
    workflow_dispatch:

concurrency:
    group: deploy-${{ github.ref }}
    cancel-in-progress: true

jobs:
    publish:
        permissions:
            contents: read
            deployments: write
        runs-on: ubuntu-latest
        name: Deploy to Cloudflare Pages
        if: ${{ github.event.head_commit.message != 'update list' }}
        steps:
            -   name: 'Checkout'
                uses: actions/checkout@v5
            -   name: Set up JDK 21
                uses: actions/setup-java@v4.0.0
                with:
                    java-version: '21'
                    distribution: 'temurin'
            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew
            -   name: Build repo
                uses: gradle/gradle-build-action@v2.11.0
                with:
                    arguments: :repo:buildRepo
            -   name: Deploy
                uses: cloudflare/wrangler-action@v3
                with:
                    apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                    accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                    gitHubToken: ${{ secrets.GITHUB_TOKEN }}
                    command: pages deploy build/repo --project-name="mewodding-repo" --commit-hash=${{ github.sha }} --branch=${{ github.ref_name }}
    update:
        permissions:
            contents: write
        name: Update list thing
        runs-on: ubuntu-latest
        needs: publish
        steps:
            -   name: 'Checkout'
                uses: actions/checkout@v5
            -   name: Set up JDK 21
                uses: actions/setup-java@v4.0.0
                with:
                    java-version: '21'
                    distribution: 'temurin'
            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew
            -   name: Build repo
                uses: gradle/gradle-build-action@v2.11.0
                with:
                    arguments: :repo:buildRepo
            -   name: Update list
                run: |
                    git config --global user.name "github-actions[bot]"
                    git config --global user.email "github-actions[bot]@users.noreply.github.com"
                    ./gradlew :repo:updateList
            -   name: Commit files
                run: |
                    git add .
                    git commit -m "update list" || echo "No changes to commit"
            -   name: Push changes
                run: |
                    git push
                env:
                    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
